version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: plotify_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
