"use client";

import { useEffect, useActionState, useTransition } from "react";
import { X } from "lucide-react";
import { Lot } from "@/types/lots.types";
import { Contribution } from "@/types/contributions.types";
import {
  createContributionAction,
  updateContributionAction,
  ContributionState,
} from "@/lib/actions/contribution-actions";
import { translations } from "@/lib/translations";

interface ContributionModalProps {
  contribution?: Contribution | null;
  onClose: () => void;
  onSuccess: (contribution: Contribution, isUpdate: boolean) => void;
  lots: Lot[];
  lotsLoading?: boolean;
}

export default function ContributionModal({
  onClose,
  contribution,
  onSuccess,
  lots,
  lotsLoading = false,
}: ContributionModalProps) {
  const initialState: ContributionState = { message: null, errors: {} };
  const action = contribution ? updateContributionAction : createContributionAction;
  const [state, formAction] = useActionState(action, initialState);
  const [isPending, startTransition] = useTransition();

  useEffect(() => {
    if (state?.success) {
      onClose();
    }
  }, [state, onClose]);

  const handleSubmit = (formData: FormData) => {
    startTransition(() => {
      const updatedContribution: Contribution = {
        id: contribution?.id || 0, // Will be generated by database for new contributions
        lotId: formData.get("lotId") as string,
        type: formData.get("type") as "maintenance" | "works",
        amount: parseFloat(formData.get("amount") as string),
        date: new Date(formData.get("date") as string),
        description: formData.get("description") as string,
      };
      onSuccess(updatedContribution, !!contribution);
      formAction(formData);
    });
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg p-6 w-full max-w-md mx-4">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-semibold">
            {contribution ? "Edit Contribution" : translations.modals.registerNewContribution}
          </h2>
          <button
            onClick={onClose}
            disabled={isPending}
            className="text-gray-400 hover:text-gray-600 disabled:opacity-50"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        <form action={handleSubmit} className="space-y-4">
          {state.message && (
            <div
              className={`text-sm mb-4 ${
                state.message.includes("successfully")
                  ? "text-green-600"
                  : "text-red-500"
              }`}
            >
              {state.message}
            </div>
          )}

          {contribution && <input type="hidden" name="id" value={contribution.id} />}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {translations.modals.lot}
            </label>
            <select
              name="lotId"
              defaultValue={contribution?.lotId || ""}
              className="w-full border rounded-sm px-3 py-2"
              required
              disabled={lotsLoading || isPending}
            >
              <option value="">
                {lotsLoading ? translations.status.loading : translations.modals.selectLot}
              </option>
              {lots.map((lot) => (
                <option key={lot.id} value={lot.id}>
                  {lot.lotNumber} - {lot.owner}
                </option>
              ))}
            </select>
            {state.errors?.lotId && (
              <div className="text-red-500 text-sm mt-1">
                {state.errors.lotId}
              </div>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {translations.modals.fundType}
            </label>
            <select
              name="type"
              defaultValue={contribution?.type || "maintenance"}
              className="w-full border rounded-sm px-3 py-2"
              required
              disabled={isPending}
            >
              <option value="maintenance">
                {translations.modals.maintenance}
              </option>
              <option value="works">{translations.modals.works}</option>
            </select>
            {state.errors?.type && (
              <div className="text-red-500 text-sm mt-1">
                {state.errors.type}
              </div>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {translations.modals.amount}
            </label>
            <input
              type="number"
              name="amount"
              defaultValue={contribution?.amount || ""}
              className="w-full border rounded-sm px-3 py-2"
              required
              min="0"
              step="1"
              disabled={isPending}
            />
            {state.errors?.amount && (
              <div className="text-red-500 text-sm mt-1">
                {state.errors.amount}
              </div>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {translations.modals.date}
            </label>
            <input
              type="date"
              name="date"
              defaultValue={contribution?.date ? contribution.date.toISOString().split('T')[0] : ""}
              className="w-full border rounded-sm px-3 py-2"
              required
              disabled={isPending}
            />
            {state.errors?.date && (
              <div className="text-red-500 text-sm mt-1">
                {state.errors.date}
              </div>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {translations.modals.description}
            </label>
            <input
              type="text"
              name="description"
              defaultValue={contribution?.description || ""}
              className="w-full border rounded-sm px-3 py-2"
              placeholder={translations.modals.optionalDescription}
              disabled={isPending}
            />
            {state.errors?.description && (
              <div className="text-red-500 text-sm mt-1">
                {state.errors.description}
              </div>
            )}
          </div>

          <div className="flex justify-end gap-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              disabled={isPending}
              className="px-4 py-2 text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50"
            >
              {translations.buttons.cancel}
            </button>
            <button
              type="submit"
              disabled={isPending}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50"
            >
              {isPending
                ? translations.status.processing
                : contribution
                ? "Update"
                : translations.buttons.saveContribution}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
