"use client";

import { useEffect, useActionState, useTransition, useRef } from "react";
import { Lot } from "@/types/lots.types";
import {
  createLotAction,
  updateLotAction,
  State,
} from "@/lib/actions/lot-actions";
import { translations } from "@/lib/translations";
import { formatDateForStorage } from "@/lib/utils";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/Dialog";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Label } from "@/components/ui/Label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/Select";
import { cn } from "@/lib/utils";

interface LotModalProps {
  lot?: Lot | null;
  onClose: () => void;
  onSuccess: (lot: Lot, isUpdate: boolean) => void;
}

export default function LotModal({ onClose, lot, onSuccess }: LotModalProps) {
  const initialState: State = { message: null, errors: {} };
  const action = lot ? updateLotAction : createLotAction;
  const [state, formAction] = useActionState(action, initialState);
  const [isPending, startTransition] = useTransition();
  const pendingLotRef = useRef<Lot | null>(null);

  useEffect(() => {
    if (state?.success) {
      if (pendingLotRef.current) {
        onSuccess(pendingLotRef.current, !!lot);
      }
      onClose();
    }
  }, [state, lot, onSuccess, onClose]);

  const handleSubmit = (formData: FormData) => {
    startTransition(() => {
      pendingLotRef.current = {
        id: lot?.id || "", // UUID will be generated by database for new lots
        lotNumber: formData.get("lotNumber") as string,
        owner: formData.get("owner") as string,
        ownerEmail: (formData.get("ownerEmail") as string) || null,
        whatsappPhone: (formData.get("whatsappPhone") as string) || null,
        initialWorksDebt:
          parseInt(formData.get("initialWorksDebt") as string) || 0,
        stage: parseInt(formData.get("stage") as string) || 1,
        maintenanceActiveFrom:
          (formData.get("maintenanceActiveFrom") as string) || null,
      };
      formAction(formData);
    });
  };

  return (
    <Dialog open={true} onOpenChange={onClose}>
      <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-md">
        <DialogHeader>
          <DialogTitle>
            {lot ? translations.titles.editLot : translations.titles.newLot}
          </DialogTitle>
        </DialogHeader>

        <form id="lot-form" action={handleSubmit} className="space-y-4">
          {state.message && (
            <div
              className={cn(
                "mb-4 text-sm",
                state.message.includes("successfully")
                  ? "text-emerald-600"
                  : "text-destructive"
              )}
            >
              {state.message}
            </div>
          )}

          {lot && <input type="hidden" name="id" value={lot.id} />}

          <div className="space-y-2">
            <Label htmlFor="lotNumber">{translations.labels.lot}</Label>
            <Input
              type="text"
              name="lotNumber"
              id="lotNumber"
              defaultValue={lot?.lotNumber || ""}
              required
              disabled={isPending}
              placeholder={translations.placeholders.lotIdExample}
            />
            {state.errors?.lotNumber && (
              <div className="text-destructive text-sm">
                {state.errors.lotNumber}
              </div>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="owner">{translations.labels.owner}</Label>
            <Input
              type="text"
              name="owner"
              id="owner"
              defaultValue={lot?.owner || ""}
              required
              disabled={isPending}
              placeholder={translations.placeholders.ownerName}
            />
            {state.errors?.owner && (
              <div className="text-destructive text-sm">
                {state.errors.owner}
              </div>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="ownerEmail">Owner Email (for access control)</Label>
            <Input
              type="email"
              name="ownerEmail"
              id="ownerEmail"
              defaultValue={lot?.ownerEmail || ""}
              disabled={isPending}
              placeholder="owner@example.com"
            />
            {state.errors?.ownerEmail && (
              <div className="text-destructive text-sm">
                {state.errors.ownerEmail}
              </div>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="initialWorksDebt">Deuda Inicial Obras (2024)</Label>
            <Input
              type="number"
              name="initialWorksDebt"
              id="initialWorksDebt"
              defaultValue={lot?.initialWorksDebt || 0}
              min="0"
              disabled={isPending}
              placeholder="0"
            />
            <p className="text-xs text-gray-600">
              Deuda inicial de obras del año 2024 para este lote
            </p>
            {state.errors?.initialWorksDebt && (
              <div className="text-destructive text-sm">
                {state.errors.initialWorksDebt}
              </div>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="stage">{translations.labels.stage}</Label>
            <Select
              name="stage"
              defaultValue={String(lot?.stage || 1)}
              disabled={isPending}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">
                  {translations.titles.quotaStage1}
                </SelectItem>
                <SelectItem value="2">
                  {translations.titles.quotaStage2}
                </SelectItem>
              </SelectContent>
            </Select>
            {state.errors?.stage && (
              <div className="text-destructive text-sm">
                {state.errors.stage}
              </div>
            )}
          </div>

          {/* WhatsApp contact */}
          <div className="space-y-2 border-t pt-4">
            <Label htmlFor="whatsappPhone">
              {translations.labels.whatsappPhone}
            </Label>
            <Input
              type="text"
              name="whatsappPhone"
              id="whatsappPhone"
              defaultValue={lot?.whatsappPhone || ""}
              disabled={isPending}
              placeholder={translations.placeholders.whatsappPhone}
              inputMode="numeric"
            />
            {state.errors?.whatsappPhone && (
              <div className="text-destructive text-sm">
                {state.errors.whatsappPhone}
              </div>
            )}
          </div>

          {/* Maintenance activation date */}
          <div className="space-y-2 border-t pt-4">
            <Label htmlFor="maintenanceActiveFrom">
              {translations.labels.maintenanceActiveFrom}
            </Label>
            <Input
              type="date"
              name="maintenanceActiveFrom"
              id="maintenanceActiveFrom"
              defaultValue={
                lot?.maintenanceActiveFrom
                  ? formatDateForStorage(lot.maintenanceActiveFrom)
                  : ""
              }
              disabled={isPending}
            />
            <p className="text-xs text-gray-600">
              Fecha desde la cual el lote empieza a deber cuotas de
              mantenimiento. Déjalo vacío si cuenta desde el inicio.
            </p>
          </div>
        </form>
        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={onClose}
            disabled={isPending}
          >
            {translations.actions.cancel}
          </Button>
          <Button type="submit" form="lot-form" disabled={isPending}>
            {isPending
              ? translations.status.processing
              : lot
                ? translations.actions.update
                : translations.actions.create}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
